use crate::idl::IdlAst;

pub struct BindingsGenerator;

impl BindingsGenerator {
    pub fn new() -> Self { Self }

    pub fn generate(&self, ast: &IdlAst, language: &str) -> Result<String, String> {
        match language {
            "rust" => self.generate_rust(ast),
            "c" | "cpp" => self.generate_c(ast),
            "python" => self.generate_python(ast),
            "ts" | "typescript" => self.generate_typescript(ast),
            "go" => self.generate_go(ast),
            l => Err(format!("unsupported language: {}", l)),
        }
    }

    fn generate_rust(&self, ast: &IdlAst) -> Result<String, String> {
        let mut out = String::from("// Generated by UDS IDL Compiler\n// DO NOT EDIT\n\n");
        for msg in &ast.messages {
            out.push_str(&format!("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n"));
            out.push_str(&format!("pub struct {} {{\n", msg.name));
            for field in &msg.fields {
                let rs_type = self.type_to_rust(&field.field_type);
                out.push_str(&format!("    pub {}: {},\n", field.name, rs_type));
            }
            out.push_str("}\n\n");
        }

        for svc in &ast.services {
            out.push_str(&format!("pub trait {}: Send + Sync {{\n", svc.name));
            for method in &svc.methods {
                let params_type = if method.params_type == "void" || method.params_type.is_empty() {
                    String::new()
                } else {
                    format!("params: &{}", method.params_type)
                };
                let return_type = if method.return_type == "void" { "()" } else { &method.return_type };
                out.push_str(&format!("    fn {}({}) -> Result<{}, uds_rpc::error::RpcError>;\n",
                    to_snake_case(&method.name), params_type, return_type));
            }
            out.push_str("}\n\n");
        }
        Ok(out)
    }

    fn generate_c(&self, ast: &IdlAst) -> Result<String, String> {
        let mut out = String::from("// Generated by UDS IDL Compiler\n// DO NOT EDIT\n\n#pragma once\n\n#include <stdint.h>\n\n");
        for msg in &ast.messages {
            out.push_str(&format!("typedef struct {{\n"));
            for field in &msg.fields {
                let c_type = self.type_to_c(&field.field_type);
                out.push_str(&format!("    {} {};\n", c_type, field.name));
            }
            out.push_str(&format!("}} {};\n\n", msg.name));
        }
        Ok(out)
    }

    fn generate_python(&self, ast: &IdlAst) -> Result<String, String> {
        let mut out = String::from("# Generated by UDS IDL Compiler\n# DO NOT EDIT\n\nfrom dataclasses import dataclass\n\n");
        for msg in &ast.messages {
            out.push_str(&format!("@dataclass\nclass {}:\n", msg.name));
            if msg.fields.is_empty() {
                out.push_str("    pass\n");
            } else {
                for field in &msg.fields {
                    let py_type = self.type_to_python(&field.field_type);
                    out.push_str(&format!("    {}: {}\n", field.name, py_type));
                }
            }
            out.push_str("\n");
        }
        Ok(out)
    }

    fn generate_typescript(&self, ast: &IdlAst) -> Result<String, String> {
        let mut out = String::from("// Generated by UDS IDL Compiler\n// DO NOT EDIT\n\n");
        for msg in &ast.messages {
            out.push_str(&format!("export interface {} {{\n", msg.name));
            for field in &msg.fields {
                let ts_type = self.type_to_ts(&field.field_type);
                let opt = if field.is_optional { "?" } else { "" };
                out.push_str(&format!("    {}{}: {};\n", field.name, opt, ts_type));
            }
            out.push_str("}\n\n");
        }
        Ok(out)
    }

    fn generate_go(&self, ast: &IdlAst) -> Result<String, String> {
        let mut out = String::from("// Generated by UDS IDL Compiler\n// DO NOT EDIT\n\npackage uds\n\n");
        for msg in &ast.messages {
            out.push_str(&format!("type {} struct {{\n", msg.name));
            for field in &msg.fields {
                let go_type = self.type_to_go(&field.field_type);
                let go_name = to_pascal_case(&field.name);
                out.push_str(&format!("    {} {} `json:\"{}\"`\n", go_name, go_type, field.name));
            }
            out.push_str("}\n\n");
        }
        Ok(out)
    }

    fn type_to_rust(&self, t: &str) -> &str {
        match t {
            "string" => "String",
            "uint32" => "u32",
            "uint16" => "u16",
            "uint8" => "u8",
            "int32" => "i32",
            "float" => "f32",
            "double" => "f64",
            "bool" => "bool",
            "bytes" => "Vec<u8>",
            _ => t,
        }
    }

    fn type_to_c(&self, t: &str) -> &str {
        match t {
            "string" => "char*",
            "uint32" => "uint32_t",
            "uint16" => "uint16_t",
            "uint8" => "uint8_t",
            "int32" => "int32_t",
            "float" => "float",
            "double" => "double",
            "bool" => "bool",
            "bytes" => "uint8_t*",
            _ => t,
        }
    }

    fn type_to_python(&self, t: &str) -> &str {
        match t {
            "string" => "str",
            "uint32" | "uint16" | "uint8" | "int32" => "int",
            "float" | "double" => "float",
            "bool" => "bool",
            "bytes" => "bytes",
            _ => "Any",
        }
    }

    fn type_to_ts(&self, t: &str) -> &str {
        match t {
            "string" => "string",
            "uint32" | "uint16" | "uint8" | "int32" => "number",
            "float" | "double" => "number",
            "bool" => "boolean",
            "bytes" => "Uint8Array",
            _ => "any",
        }
    }

    fn type_to_go(&self, t: &str) -> &str {
        match t {
            "string" => "string",
            "uint32" => "uint32",
            "uint16" => "uint16",
            "uint8" => "uint8",
            "int32" => "int32",
            "float" => "float32",
            "double" => "float64",
            "bool" => "bool",
            "bytes" => "[]byte",
            _ => "interface{}",
        }
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_ascii_lowercase());
    }
    result
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::idl::IdlParser;

    fn sample_ast() -> IdlAst {
        let input = r#"
service Device {
    rpc GetStatus() returns (Status);
}

message Status {
    string device_name;
    uint32 uptime_seconds;
    float temperature;
}
"#;
        IdlParser::new().parse(input).unwrap()
    }

    #[test]
    fn test_generate_rust() {
        let gen = BindingsGenerator::new();
        let output = gen.generate(&sample_ast(), "rust").unwrap();
        assert!(output.contains("pub struct Status"));
        assert!(output.contains("device_name: String"));
        assert!(output.contains("uptime_seconds: u32"));
    }

    #[test]
    fn test_generate_python() {
        let gen = BindingsGenerator::new();
        let output = gen.generate(&sample_ast(), "python").unwrap();
        assert!(output.contains("class Status"));
        assert!(output.contains("device_name: str"));
    }

    #[test]
    fn test_unsupported_language() {
        let gen = BindingsGenerator::new();
        let ast = IdlParser::new().parse("").unwrap();
        assert!(gen.generate(&ast, "brainfuck").is_err());
    }
}
